name = "LightsOut-Math"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["nullity2.nullity2"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "nullity2.Core"
srcDir = "tex"

[[lean_lib]]
name = "nullity2.MirroredPath"
srcDir = "tex"

[[lean_lib]]
name = "nullity2.Grid"
srcDir = "tex"

[[lean_lib]]
name = "nullity2.GridFive"
srcDir = "tex"

[[lean_lib]]
name = "nullity2.MostClicks"
srcDir = "tex"

[[lean_lib]]
name = "nullity2.GridClicks"
srcDir = "tex"

[[lean_lib]]
name = "nullity2.GridFibonacci"
srcDir = "tex"

[[lean_lib]]
name = "nullity2.GridSmallFibonacci"
srcDir = "tex"

[[lean_lib]]
name = "nullity2.GridFibonacciCertificates"
srcDir = "tex"

[[lean_lib]]
name = "nullity2.GridFibonacciFiniteGCD"
srcDir = "tex"

[[lean_lib]]
name = "nullity2.GridFibonacciFiniteRank"
srcDir = "tex"

[[lean_lib]]
name = "nullity2.GridFibonacciRoots"
srcDir = "tex"

[[lean_lib]]
name = "nullity2.GridFibonacciRank"
srcDir = "tex"

[[lean_lib]]
name = "nullity2.OreGCD"
srcDir = "tex"

[[lean_lib]]
name = "nullity2.GridNullityRecurrence"
srcDir = "tex"

[[lean_lib]]
name = "nullity2.GridNullityValues"
srcDir = "tex"

[[lean_lib]]
name = "nullity2.GridNullityTwentySix"
srcDir = "tex"

[[lean_lib]]
name = "nullity2.GridNullityClicks"
srcDir = "tex"

[[lean_lib]]
name = "nullity2.nullity2"
srcDir = "tex"
