import Mathlib.FieldTheory.Finite.Trace

/-! Trace in a finite field generated by an algebraic element. -/

namespace LightsOutNumberTheory

open IntermediateField

/-- Definition 4.8 (`fieldTrace`) of `finite_fields.tex`: the trace from
`F(a)` to a finite field `F` is mathlib's `Algebra.trace F F⟮a⟯`.
Under the algebra map into `F(a)`, it is the sum of the Frobenius powers
of `z`. The integrality hypothesis ensures that `F(a)` is finite. -/
theorem trace_adjoin_eq_sum_pow {F L : Type*}
    [Field F] [Finite F] [Field L] [Algebra F L]
    (a : L) (ha : IsIntegral F a) (z : F⟮a⟯) :
    algebraMap F F⟮a⟯ (Algebra.trace F F⟮a⟯ z) =
      ∑ r ∈ Finset.range (Module.finrank F F⟮a⟯),
        z ^ (Nat.card F ^ r) := by
  have : FiniteDimensional F F⟮a⟯ :=
    IntermediateField.finiteDimensional_adjoin (S := {a}) (by simpa using ha)
  have : Finite F⟮a⟯ := Module.finite_of_finite F
  exact FiniteField.algebraMap_trace_eq_sum_pow F F⟮a⟯ z

/-- The Frobenius-sum formula after embedding `F(a)` into the ambient field. -/
theorem trace_adjoin_eq_sum_pow_in_ambient {F L : Type*}
    [Field F] [Finite F] [Field L] [Algebra F L]
    (a : L) (ha : IsIntegral F a) (z : F⟮a⟯) :
    algebraMap F L (Algebra.trace F F⟮a⟯ z) =
      ∑ r ∈ Finset.range (Module.finrank F F⟮a⟯),
        (z : L) ^ (Nat.card F ^ r) := by
  have htr := trace_adjoin_eq_sum_pow a ha z
  have hcast := congrArg (fun w : F⟮a⟯ => (w : L)) htr
  simpa [IsScalarTower.algebraMap_apply, map_sum] using hcast

/-- Corollary 4.9 (`traceAt1`) of `finite_fields.tex`: the trace of one
from `F(a)` to `F` is the extension degree, viewed as an element of `F`. -/
theorem trace_adjoin_one {F L : Type*}
    [Field F] [Finite F] [Field L] [Algebra F L]
    (a : L) (ha : IsIntegral F a) :
    Algebra.trace F F⟮a⟯ (1 : F⟮a⟯) =
      (Module.finrank F F⟮a⟯ : F) := by
  apply (FaithfulSMul.algebraMap_injective F F⟮a⟯)
  simpa using trace_adjoin_eq_sum_pow a ha (1 : F⟮a⟯)

end LightsOutNumberTheory
