import Mathlib.FieldTheory.Finite.Basic
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import nullity2.SignedOrder

/-! The degree of the field generated by a root-of-unity trace in
characteristic two. -/

namespace LightsOutNumberTheory

open IntermediateField

private theorem add_inv_eq_add_inv_iff {K : Type*} [Field K] [CharP K 2]
    (a b : K) (ha : a ≠ 0) (hb : b ≠ 0) :
    a + a⁻¹ = b + b⁻¹ ↔ a = b ∨ a = b⁻¹ := by
  have he : (a + b) * (a * b + 1) =
      a * b * ((a + a⁻¹) + (b + b⁻¹)) := by
    field_simp
    ring
  constructor
  · intro h
    have hs : (a + b) * (a * b + 1) = 0 := by
      rw [he, h, CharTwo.add_self_eq_zero, mul_zero]
    rcases mul_eq_zero.mp hs with hh | hh
    · exact Or.inl (by simpa only [CharTwo.neg_eq] using
        eq_neg_of_add_eq_zero_left hh)
    · right
      have heq : a * b = 1 := by
        simpa only [CharTwo.neg_eq] using eq_neg_of_add_eq_zero_left hh
      exact (mul_eq_one_iff_eq_inv₀ hb).mp heq
  · rintro (rfl | rfl)
    · rfl
    · simp [add_comm]

private theorem pow_eq_self_iff {K : Type*} [Field K]
    (z : K) (hz : z ≠ 0) (m : ℕ) (hm : 0 < m) :
    z ^ m = z ↔ z ^ (m - 1) = 1 := by
  have he : z ^ (m - 1) * z = z ^ m := pow_sub_one_mul (by omega) z
  constructor
  · intro h
    apply mul_right_cancel₀ hz
    simpa only [he, one_mul] using h
  · intro h
    rw [← he, h, one_mul]

private theorem root_power_eq_self_iff {K : Type*} [Field K]
    (z : K) (hz : z ≠ 0) (M r : ℕ) (horder : orderOf z = M) :
    z ^ (2 ^ r) = z ↔ (2 : ZMod M) ^ r = 1 := by
  have hmod : (2 : ZMod M) ^ r = 1 ↔ M ∣ 2 ^ r - 1 := by
    have hge : 1 ≤ 2 ^ r := one_le_pow₀ (by decide)
    calc
      (2 : ZMod M) ^ r = 1 ↔
          ((1 : ℕ) : ZMod M) = ((2 ^ r : ℕ) : ZMod M) := by
            simp only [Nat.cast_pow, Nat.cast_ofNat, Nat.cast_one, eq_comm]
      _ ↔ 1 ≡ 2 ^ r [MOD M] := ZMod.natCast_eq_natCast_iff 1 (2 ^ r) M
      _ ↔ M ∣ 2 ^ r - 1 := Nat.modEq_iff_dvd' hge
  calc
    z ^ (2 ^ r) = z ↔ z ^ (2 ^ r - 1) = 1 :=
      pow_eq_self_iff z hz _ (pow_pos (by decide) _)
    _ ↔ M ∣ 2 ^ r - 1 := by rw [← horder, orderOf_dvd_iff_pow_eq_one]
    _ ↔ (2 : ZMod M) ^ r = 1 := hmod.symm

private theorem root_power_eq_inv_iff {K : Type*} [Field K]
    (z : K) (hz : z ≠ 0) (M r : ℕ) (horder : orderOf z = M) :
    z ^ (2 ^ r) = z⁻¹ ↔ (2 : ZMod M) ^ r = -1 := by
  have hmod : (2 : ZMod M) ^ r = -1 ↔ M ∣ 2 ^ r + 1 := by
    have hcast : ((2 ^ r + 1 : ℕ) : ZMod M) =
        (2 : ZMod M) ^ r + 1 := by push_cast; rfl
    rw [eq_neg_iff_add_eq_zero, ← hcast]
    exact ZMod.natCast_eq_zero_iff (2 ^ r + 1) M
  calc
    z ^ (2 ^ r) = z⁻¹ ↔ z ^ (2 ^ r + 1) = 1 := by
      rw [pow_succ, mul_eq_one_iff_eq_inv₀ hz]
    _ ↔ M ∣ 2 ^ r + 1 := by rw [← horder, orderOf_dvd_iff_pow_eq_one]
    _ ↔ (2 : ZMod M) ^ r = -1 := hmod.symm

/-- The sum of a finite-order element and its inverse is integral over the
base field. -/
theorem isIntegral_add_inv_of_orderOf {K : Type*}
    [Field K] [Algebra (ZMod 2) K] (ζ : K) {M : ℕ}
    (hM : 0 < M) (hζ : orderOf ζ = M) :
    IsIntegral (ZMod 2) (ζ + ζ⁻¹) := by
  have hpow : ζ ^ M = 1 := by
    rw [← hζ]
    exact pow_orderOf_eq_one ζ
  have hζint : IsIntegral (ZMod 2) ζ :=
    IsIntegral.of_pow hM (by rw [hpow]; exact isIntegral_one)
  have hζinvint : IsIntegral (ZMod 2) ζ⁻¹ :=
    IsIntegral.of_pow hM
      (by rw [inv_pow, hpow, inv_one]; exact isIntegral_one)
  exact hζint.add hζinvint

/-- Lemma 4.7 (`fieldExtensionSize`) of `finite_fields.tex`: for an odd
`M > 1` and an element `ζ` of exact order `M` in characteristic two,
the degree of `𝔽₂(ζ + ζ⁻¹)` is the signed order of two modulo `M`.
The ambient field need not itself be finite or algebraically closed. -/
theorem finrank_adjoin_add_inv_eq_signedOrder {K : Type*}
    [Field K] [CharP K 2] [Algebra (ZMod 2) K]
    {M : ℕ} (hM : 1 < M) (hModd : Odd M) {ζ : K}
    (hζ : orderOf ζ = M) :
    Module.finrank (ZMod 2)
        (IntermediateField.adjoin (ZMod 2) ({ζ + ζ⁻¹} : Set K)) =
      signedOrder 2 M (Nat.coprime_two_left.mpr hModd) := by
  let α := ζ + ζ⁻¹
  have hζ0 : ζ ≠ 0 := by
    intro hzero
    have hz := hζ
    rw [hzero, orderOf_zero] at hz
    omega
  have hαint : IsIntegral (ZMod 2) α :=
    isIntegral_add_inv_of_orderOf ζ (by omega) hζ
  let F : IntermediateField (ZMod 2) K := (ZMod 2)⟮α⟯
  let a : F := ⟨α, IntermediateField.mem_adjoin_simple_self (ZMod 2) α⟩
  have : FiniteDimensional (ZMod 2) F :=
    IntermediateField.finiteDimensional_adjoin (S := {α}) (by simpa using hαint)
  have : Finite F := Module.finite_of_finite (ZMod 2)
  let φ : F →ₐ[ZMod 2] F := FiniteField.frobeniusAlgHom (ZMod 2) F
  have heval (r : ℕ) : (φ ^ r) a = a ^ (2 ^ r) := by
    change ((FiniteField.frobeniusAlgHom (ZMod 2) F) ^ r) a = a ^ (2 ^ r)
    simp [AlgHom.coe_pow, FiniteField.coe_frobeniusAlgHom, pow_iterate,
      show Fintype.card (ZMod 2) = 2 by decide]
  have hperiod (r : ℕ) : φ ^ r = 1 ↔ α ^ (2 ^ r) = α := by
    have hsub : a ^ (2 ^ r) = a ↔ α ^ (2 ^ r) = α := by
      constructor
      · intro h
        exact congrArg (fun z : F => (z : K)) h
      · intro h
        exact Subtype.ext h
    rw [← hsub]
    constructor
    · intro h
      have he := congrArg (fun f : F →ₐ[ZMod 2] F => f a) h
      simpa only [heval, AlgHom.one_apply] using he
    · intro h
      apply IntermediateField.adjoin_algHom_ext (ZMod 2)
      intro x hx
      have he : x = α := by simpa using hx
      subst x
      change (φ ^ r) a = a
      rw [heval]
      exact h
  have hchar (r : ℕ) :
      α ^ (2 ^ r) = α ↔
        (2 : ZMod M) ^ r = 1 ∨ (2 : ZMod M) ^ r = -1 := by
    have hzpow : ζ ^ (2 ^ r) ≠ 0 := pow_ne_zero _ hζ0
    change (ζ + ζ⁻¹) ^ (2 ^ r) = ζ + ζ⁻¹ ↔ _
    rw [add_pow_char_pow, inv_pow,
      add_inv_eq_add_inv_iff (ζ ^ (2 ^ r)) ζ hzpow hζ0,
      root_power_eq_self_iff ζ hζ0 M r hζ,
      root_power_eq_inv_iff ζ hζ0 M r hζ]
  let hcop : (2 : ℕ).Coprime M := Nat.coprime_two_left.mpr hModd
  let ρ := signedOrder 2 M hcop
  have hρpos : 0 < ρ := (signedOrder_spec 2 M hcop).1
  have hρspec := (signedOrder_spec 2 M hcop).2
  have hdegree : orderOf φ = Module.finrank (ZMod 2) F :=
    FiniteField.orderOf_frobeniusAlgHom (ZMod 2) F
  have hdeg_le : Module.finrank (ZMod 2) F ≤ ρ := by
    have hfix : φ ^ ρ = 1 := (hperiod ρ).mpr ((hchar ρ).mpr hρspec)
    exact Nat.le_of_dvd hρpos (hdegree ▸
      (orderOf_dvd_iff_pow_eq_one).mpr hfix)
  have hρ_le : ρ ≤ Module.finrank (ZMod 2) F := by
    have hpos : 0 < Module.finrank (ZMod 2) F := Module.finrank_pos
    have hfix : α ^ (2 ^ Module.finrank (ZMod 2) F) = α :=
      (hperiod _).mp (by rw [← hdegree]; exact pow_orderOf_eq_one φ)
    exact signedOrder_le_of_pow_eq_one_or_neg_one 2 M hcop
      (Module.finrank (ZMod 2) F) hpos ((hchar _).mp hfix)
  exact le_antisymm hdeg_le hρ_le

end LightsOutNumberTheory
